package com.yarncoms.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

import com.yarncoms.model.EnquiryTable;
import com.yarncoms.model.YarnBase;
import com.yarncoms.service.CustomerService;
import com.yarncoms.service.EnquiryTableService;

/**
 * A Spring controller that allows the users to download an Excel document
 * generated by the Apache POI library.
 *
 * @author www.codejava.net
 *
 */
@CrossOrigin(origins = "http:\\localhost:4200")
@Controller
@RequestMapping("/rest")
public class MainController {

	@Autowired
	private EnquiryTableService EnquiryTableServiceImpl;
	
	@Autowired
	private CustomerService customerService;

	@RequestMapping(value = "downloadExcell", method = RequestMethod.GET)
	public ModelAndView downloadExcel() {

		List<YarnBase> listBooks = new ArrayList<YarnBase>();

		List<EnquiryTable> EnquiryTable = EnquiryTableServiceImpl.list();

		System.out.println(EnquiryTable.get(0).getEnquiryId() + " " + EnquiryTable.get(0).getEnquiryFrom() + " "
				+ EnquiryTable.get(0).getEnquiryFor() + " " + EnquiryTable.get(0).getBrand() + " "
				+ EnquiryTable.get(0).getCompanyName() + " " + EnquiryTable.get(0).getContactPersonName() + " "
				+ EnquiryTable.get(0).getContactPersonEmail() + " " + EnquiryTable.get(0).getCountryCode() + " "
				+ EnquiryTable.get(0).getContactNo() + " " + EnquiryTable.get(0).getTechnicalPerson() + " "
				+ EnquiryTable.get(0).getEnqDate() + " " + EnquiryTable.get(0).getEnqStatus() + " "
				+ EnquiryTable.get(0).getEnqLevel() + " " + EnquiryTable.get(0).getReasonforClosing() + " "
				+ EnquiryTable.get(0).getCount() + " " + EnquiryTable.get(0).getWarpCount() + " "
				+ EnquiryTable.get(0).getWeftCount() + " " + EnquiryTable.get(0).getProductDescription() + " "
				+ EnquiryTable.get(0).getRemarks());

		/*listBooks.add(new YarnBase(EnquiryTable.get(0).getEnquiryId(), EnquiryTable.get(0).getEnquiryFrom(),
				EnquiryTable.get(0).getEnquiryFor(), EnquiryTable.get(0).getBrand(),
				EnquiryTable.get(0).getCompanyName(), EnquiryTable.get(0).getContactPersonName(),
				EnquiryTable.get(0).getContactPersonEmail(), EnquiryTable.get(0).getCountryCode(),
				EnquiryTable.get(0).getContactNo(), EnquiryTable.get(0).getTechnicalPerson(),
				EnquiryTable.get(0).getEnqDate(), EnquiryTable.get(0).getEnqStatus(), EnquiryTable.get(0).getEnqLevel(),
				EnquiryTable.get(0).getReasonforClosing(), EnquiryTable.get(0).getCount(),
				EnquiryTable.get(0).getWarpCount(), EnquiryTable.get(0).getWeftCount(),
				EnquiryTable.get(0).getProductDescription(), EnquiryTable.get(0).getRemarks()));*/

		ExcelBuilder excel = new ExcelBuilder();

		// return a view which will be resolved by an excel view resolver
		return new ModelAndView(excel, "listBooks", listBooks);
	}
}